### ISSUE TITLE
mention no indirect; as a generic detection method?

### ISSUE THREAD

**Issue by tm604** [bluefeet/Perl-Critic-Policy-TryTiny-RequireUse#1]
Hi there,

The 'indirect' module covers try {} as well as other functions, such as List::Util any(), Future::Utils fmap, etc.: https://metacpan.org/pod/indirect

There's a perlcritic policy as well: https://metacpan.org/pod/Perl::Critic::Policy::Dynamic::NoIndirect

Worth mentioning these in a SEE ALSO section?

cheers,

Tom

**Comment by bluefeet** [comment]
Thanks!
