### ISSUE TITLE
Other exporters of try

### ISSUE THREAD

**Issue by Grinnz** [bluefeet/Perl-Critic-Policy-TryTiny-RequireUse#2]
These exporters should probably also be recognized.
- Try
- Syntax::Feature::Try (used as `use syntax 'try'`)
- Error (ancient and terrible, but valid; better caught by https://metacpan.org/pod/Perl::Critic::Policy::Freenode::DiscouragedModules#Error :)

**Comment by bluefeet** [comment]
Thank you very much for letting me know!
